#Calculate the output of the neuron Y for the network shown below. Use binary and bipolar
#sigmodial activation function.
import math
print("Input x1= ")
x1=float(input())
print("Input x2= ")
x2=float(input())
print("Input weight w1= ")
w1=float(input())
print("Input weight w2= ")
w2=float(input())
print("Input Bias b=")
b=float(input())
print()
yin=b+(x1*w1+x2*w2)
y1=1/(1 + math.exp(-yin))
y2=(2/(1 + math.exp(-yin)))-1
print("Inputs are: ")
print("x1=",x1)
print("x2=",x2,'\n')
print("Weights are:")
print("w1=",w1)
print("w2=",w2,'\n')
print("Bias b=",b)
print("Net Input=",yin,'\n')
print("Binary Sigmodial Activation Function")
print("Output=",y1,'\n')
print("Bipolar Sigmodial Activation Function")
print("Output=",y2)